In [28]:
import numpy as np

In [29]:
mylist=[1,3,5,6]

In [30]:
type(mylist)

list

In [31]:
np.array(mylist)

array([1, 3, 5, 6])

In [32]:
type(mylist)

list

In [33]:
arr=np.array(mylist)

In [34]:
arr

array([1, 3, 5, 6])

In [35]:
mylist=[[1,3,5],[4,5,6],[1,4,76],[1,3,5]]

In [36]:
mylist

[[1, 3, 5], [4, 5, 6], [1, 4, 76], [1, 3, 5]]

In [37]:
np.array(mylist)

array([[ 1,  3,  5],
       [ 4,  5,  6],
       [ 1,  4, 76],
       [ 1,  3,  5]])

In [38]:
mymatrix=np.array(mylist)

In [39]:
mymatrix.shape

(4, 3)

In [40]:
mynewmatrix=np.array(mylist)
mynewmatrix

array([[ 1,  3,  5],
       [ 4,  5,  6],
       [ 1,  4, 76],
       [ 1,  3,  5]])

In [41]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [43]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [44]:
type(0.)

float

In [45]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
np.ones((5,5)) +5

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [47]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [48]:
np.ones(4)/100

array([0.01, 0.01, 0.01, 0.01])

In [54]:
np.linspace(0,30,3)

array([ 0., 15., 30.])

In [50]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [51]:
len(np.linspace(0,10,20))

20

In [52]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# numpy arrys

In [55]:
np.random.rand(1)

array([0.41872038])

In [56]:
np.random.rand(3,5)

array([[0.60613727, 0.61471441, 0.60561993, 0.97166717, 0.85948577],
       [0.84504367, 0.58911886, 0.94884461, 0.46177559, 0.93109635],
       [0.85142355, 0.41696166, 0.53894348, 0.00121356, 0.73646186]])

In [57]:
np.random.randn(5)

array([-0.06968929, -0.36458639,  0.37634114, -0.81216602,  0.31950337])

In [58]:
np.random.randint(1,100,5)

array([64, 84, 87, 12, 65])

In [60]:
np.random.seed(24)


In [62]:
np.random.rand(4)

array([0.36105635, 0.73984099, 0.99645573, 0.31634698])

In [63]:
np.random.rand(4)

array([0.13654458, 0.38398001, 0.32051928, 0.36641475])

In [64]:
np.random.rand(4)

array([0.70965156, 0.90014243, 0.53411544, 0.24729376])

In [65]:
arr=np.arange(25)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [107]:
arr1=np.random.randint(0,50,16)

In [108]:
arr1

array([ 2, 43, 36, 45, 32, 22, 34, 11, 30, 21, 39,  4,  3, 43,  7,  8])

In [109]:
arr1.shape

(16,)

In [111]:
arr1.reshape(4,4)

array([[ 2, 43, 36, 45],
       [32, 22, 34, 11],
       [30, 21, 39,  4],
       [ 3, 43,  7,  8]])

In [72]:
arr1.max()

47

In [73]:
arr1.min()

1

In [74]:
arr1

array([31, 33,  1,  6, 33, 17,  6, 46,  1, 47])

In [75]:
arr1.argmax()

9

In [76]:
arr1.argmin()

2

In [77]:
arr1.dtype

dtype('int32')

# numpy indeximg and selection

In [112]:
import numpy as np


In [113]:
arr=np.arange(11)

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr[8]

8

In [116]:
arr[2]

2

In [117]:
arr[1:5]

array([1, 2, 3, 4])

In [118]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [120]:
arr[:5]

array([0, 1, 2, 3, 4])

In [87]:
arr[4:7]

array([4, 5, 6])

In [88]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [89]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [91]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [92]:
arr+100 / 2

array([50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60.])

In [93]:
new_arr=arr / 2

In [94]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [121]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
slice_of_arr=arr[0:8]

In [123]:
slice_of_arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [124]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [125]:
slice_of_arr[:]=100

In [126]:
slice_of_arr

array([100, 100, 100, 100, 100, 100, 100, 100])

In [127]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100,   8,   9,  10])

In [128]:
arr_copy = arr.copy()

In [129]:
arr_copy[:]=100

In [130]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [131]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100,   8,   9,  10])

## INDEXING on 2D array

In [132]:
arr_2d=np.array([[1,45,5],[2,45,6],[7,8,9]])

In [133]:
arr_2d

array([[ 1, 45,  5],
       [ 2, 45,  6],
       [ 7,  8,  9]])

In [134]:
arr_2d.shape


(3, 3)

In [135]:
arr_2d[1]

array([ 2, 45,  6])

In [136]:
arr_2d[1][0]

2

In [137]:
arr_2d[1][1]

45

In [138]:
arr_2d[1,1]

45

In [139]:
arr_2d

array([[ 1, 45,  5],
       [ 2, 45,  6],
       [ 7,  8,  9]])

In [140]:
arr_2d[:2]

array([[ 1, 45,  5],
       [ 2, 45,  6]])

In [141]:
arr_2d[:2,1:]

array([[45,  5],
       [45,  6]])

In [142]:
arr=np.arange(11)

In [143]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
arr < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False])

In [145]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [146]:
bool_arr= arr>4

In [147]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [148]:
arr[bool_arr]  #condition seletion

array([ 5,  6,  7,  8,  9, 10])

In [149]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [150]:
arr[arr ==2]

array([2])

In [151]:
arr[arr <=4]

array([0, 1, 2, 3, 4])

## numpy operation

In [152]:
import numpy as np

In [153]:
arr=np.arange(10)

In [154]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [156]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [157]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [158]:
(arr+2)/2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [159]:
(arr+2)-2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [161]:
arr/0

C:\Users\hp\AppData\Local\Temp\ipykernel_5972\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0
C:\Users\hp\AppData\Local\Temp\ipykernel_5972\4291252909.py:1: RuntimeWarning: invalid value encountered in divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [162]:
1/arr

C:\Users\hp\AppData\Local\Temp\ipykernel_5972\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [163]:
arr/arr #bcoz zero are presnt in the array

C:\Users\hp\AppData\Local\Temp\ipykernel_5972\91700794.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr #bcoz zero are presnt in the array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [164]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [165]:
np.log(arr) #bcz first no is zro its makes it infinity

C:\Users\hp\AppData\Local\Temp\ipykernel_5972\3565305275.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) #bcz first no is zro its makes it infinity


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [166]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [167]:
arr.sum()

45

In [168]:
arr.max()

9

In [169]:
arr.mean()

4.5

In [170]:
arr_2d=np.array([[1,2,3],[2,2,3],[34,5,7]])

In [171]:
arr_2d

array([[ 1,  2,  3],
       [ 2,  2,  3],
       [34,  5,  7]])

In [172]:
arr_2d.sum()

59

In [173]:
arr_2d.shape

(3, 3)

In [174]:
arr_2d.sum()

59

In [175]:
# give me sum acroos the rows
arr_2d.sum(axis=0) 
    #array  along the vertical axis when axis=0 that count colum element
  #mean that produce the sum of the coluam  

array([37,  9, 13])

In [176]:
arr_2d.sum(axis=1)

array([ 6,  7, 46])

## numpy exericses 

In [177]:
import numpy as np

## create an array of 10 zeros

In [178]:
arr=np.zeros(10)

In [179]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## create an array of 10 ones

In [180]:
arr=np.ones(10)

In [181]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## create an array of 10 fives 

In [182]:
arr=np.ones(10)*5

In [183]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## craete an array of  integer  from 10 to 50

In [184]:
arr=np.arange(10,51)

In [185]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

## create an array of all even integer from 10 to 50

In [186]:
arr=np.arange(10,51,2)

In [187]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

## create 3x3 matrix with the values ranging of 0 to 8

In [188]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [189]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [190]:
matrix = np.arange(9).reshape((3, 3))

In [191]:
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [192]:
matrix = np.arange(16)
matrix.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## create 3x3 identity matrix

In [193]:
identity_matrix = np.identity(3)
identity_matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [194]:
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [195]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [196]:
arr=np.random.rand(1)

In [197]:
arr

array([0.61287885])

In [198]:
random_matrix = np.random.randn(25)

In [199]:
random_matrix

array([-0.38124668,  0.36649793,  0.99719722,  0.390556  , -0.16061569,
       -0.07517978, -2.83762557, -0.40001494,  0.6088537 ,  1.28285909,
        2.58375322, -1.51982897, -1.29107222, -2.40321112, -0.95943038,
        0.04551242,  1.19264644,  2.03161348, -1.71346876, -0.47223365,
        0.5494507 ,  0.3608764 ,  0.09430229,  0.74012362, -0.49900464])

In [200]:
arr=np.arange(1,101)

In [201]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [202]:
arr=np.arange(1,101)/100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [203]:
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

## create an arry of 20 linearly spaced point b/w 0 and 1

In [204]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## numpy indexing and selection

In [205]:
mat=np.arange(1,26).reshape(5,5)

In [206]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [207]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [208]:
mat[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [209]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [210]:
mat[3,4]

20

In [211]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [212]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [213]:
mat.sum()

325

In [214]:
mat.std()

7.211102550927978

In [215]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [216]:
np.random.seed(101)

In [217]:
np.random.rand(1)

array([0.51639863])